import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import Navbar from "@/components/primitives/Navbar";
import Sidebar from "@/components/primitives/Sidebar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <Providers>
                <body
                    className={`${geistSans.variable} ${geistMono.variable} antialiased p-4 md:px-20 flex flex-col justify-start items-start bg-slate-100 dark:bg-slate-900 lg:h-svh`}
                >
                    <header className="w-full">
                        {/* nav bar ... (top) */}
                        <Navbar />
                    </header>

                    {/* ?? only on course page */}
                    {/*
                 <main className="flex-1 flex flex-row py-2 md:py-6 ">
                    ?? side bar is auth props: !!
                    <Sidebar /> 
                </main> 
                */}

                    {children}

                    <footer className="w-full min-h-24 p-6 md:px-12  rounded-xl shadow-sm shadow-inherit  border border-slate-300 dark:border-slate-800 bg-slate-50 dark:bg-slate-800">
                        {/* footer*/}
                    </footer>
                </body>
            </Providers>
        </html>
    );
}
